# https://github.com/conda/conda/blob/main/tests/conda_env/support/advanced-pip/environment.yml
# https://anaconda.org/conda-forge/diffusers
# https://github.com/huggingface/diffusers/releases/tag/v0.7.0
# https://github.com/huggingface/diffusers/releases/tag/v0.7.1
# https://github.com/huggingface/diffusers/releases/tag/v0.7.2

name: img-gen-playground
channels:
  - conda-forge
dependencies:
  - python=3.7.12
  - pip=22.0.2
  - black=22.3.0
  - isort=5.10.1
  - pip:
      - diffusers[torch]==0.7.2
      - transformers==4.24.0
      - scipy==1.7.3
